### ISSUE TITLE
Returned type for math.pow(int, int) differs between Python and JS

### ISSUE THREAD

**Issue by CarstenGrohmann** [TranscryptOrg/Transcrypt#529]
Hi,

the returned types differs sometimes between the Python function `math.pow()` and the generated JS code.

Pythons `math.pow()` returns always a float and JS just if at least one of the parameters a float, that can't be converted to an interger.

Testlet output:
```
myproj/testlet_pow.py:4	'2 ** 2 = 4'	'2 ** 2 = 4'	autotest.js:2622
!!!myproj/testlet_pow.py:5	'math.pow(2, 2) = 4.0'	'math.pow(2, 2) = 4'	autotest.js:2622
myproj/testlet_pow.py:6	'math.pow(3, 2.9) = 24.190878415700578'	'math.pow(3, 2.9) = 24.190878415700578'	autotest.js:2622
!!!myproj/testlet_pow.py:7	'math.pow(3, 2.0) = 9.0'	'math.pow(3, 2.0) = 9'	autotest.js:2622
myproj/testlet_pow.py:8	'math.pow(3.1, 2.0) = 9.610000000000001'	'math.pow(3.1, 2.0) = 9.610000000000001'	autotest.js:2622
```

Testlet to reproduce the issue:
```
import math

def run(autoTester):
    autoTester.check('2 ** 2 = {}'.format(2 ** 2))
    autoTester.check('math.pow(2, 2) = {}'.format(math.pow(2, 2)))
    autoTester.check('math.pow(3, 2.9) = {}'.format(math.pow(3, 2.9)))
    autoTester.check('math.pow(3, 2.0) = {}'.format(math.pow(3, 2.0)))
    autoTester.check('math.pow(3.1, 2.0) = {}'.format(math.pow(3.1, 2.0)))
```
Is this a bug or just a type converting feature?

Regards,
Carsten

**Comment by JennaSys** [comment]
I believe this to be a limitation of JavaScript since it treats `int` and `float` simply as `number`, and a float that has zero as the decimal part gets changed to an int. 
```javascript
x = 2.0
console.log(x)
// 2
```

Both CPython and JavaScript treat _2.0_ and _2_ as numerically equivalent (`2.0 == 2` -> `True` and `2.0 === 2` -> `true`), so perhaps this may just be more of a formatting issue. Even the `Number.isInteger()` function in JS indicates _2.0_ as an int. As such, I'm inclined to leave this as a limitation.
