### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by frederickavita** [TranscryptOrg/Transcrypt#556]
transcrypt -b -m -n hello.py

File "/usr/local/bin/transcrypt", line 7, in <module>
    from transcrypt.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/transcrypt/__main__.py", line 77
    with tokenize.open (f'{modulesDir}/org/transcrypt/__envir__.js') as envirFile:

SyntaxError: invalid syntax

**Comment by JdeH** [comment]
Which version of Transcrypt are you using?

**Comment by frederickavita** [comment]
Transcrypt (3.7.4)

**Comment by frederickavita** [comment]
jacques i need transcrypt i must put an application online for tomorrow lol

**Comment by frederickavita** [comment]
shame on me i'm an idiot over 5 years of python make a mistake like that.

**Comment by JdeH** [comment]
If you have to deliver tomorrow, you may also install the TS version you were  using before under Python 3.5.

See:

https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip

All old versions are still available.

**Comment by JdeH** [comment]
You don't want to know the kind of mistakes I make.
Yesterday I've been bug hunting for 3 hours.
Turned out to be a missing underscore...

**Comment by frederickavita** [comment]
lol

**Comment by JdeH** [comment]
By the way, in dutch the word 'lol' means fun, literally, not as an abbreviation.

**Comment by g40** [comment]
> **Let me know if it works.**

@JdeH This **really** wants to be the very first thing people read in a 'how-to'. I've spent all afternoon trying to resolve an 

`uncaught referenceError` 

that was due to the missing 

`window.hello = hello`

Just the kind of thing to snare a C++ guy.

Documentation lag apart this is really nifty stuff. Thank you.

**Comment by JdeH** [comment]
@g40:
Turned out that all the examples on the site were still done with the old version of Transcrypt without modules, it's corrected now.
If you still encounter problems like this, please let us know.
Such things are crucial to newcomers to Transcrypt.
By the way, it's a pleasure to encounter someone who's into C++.
Have been using that language ever since its birth.
Still a solid powerhouse comparable to nothing.

**Comment by g40** [comment]
@JdeH Thanks for the update. I am still working through my web 'application', which uses [W2UI](http://w2ui.com/web/)  and  websockets to talk to various servers. It might make for a useful end-to-end example. Would that be of interest? Please feel free to contact me offline (g4 at novadsp dot com) if so. Thanks again for listening.

**Comment by JennaSys** [comment]
Closing since no further comments for a while now.
