### ISSUE TITLE
3.7.5 : es5 generates es6 keywords

### ISSUE THREAD

**Issue by bradiso** [TranscryptOrg/Transcrypt#563]
Dunno whether or not you plan to remove es5 from 3.7 branch, but the es5 generated code currently contains es6 keywords, mainly "let" (I'm not an expert).

**Comment by JdeH** [comment]
Yes it is intended to remove es5 from the 3.7 branch, since es5 lacks native modules.
There are still leftovers in the code and  docs though.
Thanks!

**Comment by faerot** [comment]
I am recently returned to using transcrypt, updated to the latest version and now it generates dozens of separate files instead of single minified file which was better imo as it loads faster. Is there an option to switch that mode back and if not, can you suggest how to achieve the same effect? (Tools etc.)

**Comment by faerot** [comment]
Also whis was the latest version which supported this behavior?

**Comment by JdeH** [comment]
@faerot
 
There are tools to turn it into one file.
**The idea is to integrate this into Transcrypt in medium term, so possibly within a few months.**
As these tools also perform treeshaking, the result will even be smaller than before.

One such tool is Rollup:

https://rollupjs.org/guide/en

Since it requires node.js, it isn't part of the repo / distro.

The following fragment of ../development/shipment/shipment_test.py shows how it's used:

    # ---- Apply rollup to obtain monolith, since node doesn't support named imports and exports
    
    if nodeJs:
        os.system (f'rollup {targetPrepath}.js --o {targetPrepath}.bundle.js --f cjs')
    
    if not commandArgs.blind:
        if nodeJs:
            os.system (f'start cmd /k node {targetPrepath}.bundle.js'.format (moduleName))
            time.sleep (5)
            url = nodeServerUrl
        else:
            url = f'{pythonHttpServerUrl}/{relSourcePrepath}.html'
            
        success = browserController.open (url, run)

Hope that helps you out for now.
Indeed generating a monolith rather than modules is better in some cases.
Let me know if this works for you.

Kind regards
Jacques

**Comment by JennaSys** [comment]
Closing since no further comments, but I'll also mention that there are a number of very effective JavaScript bundlers that exist in the JS ecosystem and I think it makes more sense to utilize those than to try and incorporate that functionality directly into Transcrypt.
