### ISSUE TITLE
Benchmark: Brython vs Transcrypt

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [TranscryptOrg/Transcrypt#661]
1. re: Benchmark request #459

2. would it be possible to have extended Benchmark: Brython vs Transcrypt, i.e.:

https://brythonista.wordpress.com/2015/03/28/comparing-the-speed-of-cpython-brython-skulpt-and-pypy-js/

**Comment by fzzylogic** [comment]
Benchmarks can't show the full picture, but if you want to try this at home, save that benchmark code locally, then:

    pip install transcrypt
    transcrypt bench_str.py

Then make some html with this body (note type="module", so use ES6 supporting browser):

    <div id="__terminal__"></div>
    <script type="module" src="__target__/bench_str.js"></script>

Setting id to __terminal__ is a transcrypt feature that will show anything that was printed in the DOM element with that id. Otherwise, it goes to the console.

Finally, serve it, so modules can be loaded:

    python -m http.server 8005

**Comment by DonaldTsang** [comment]
@Andrei-Pozolotin @fzzylogic requesting https://github.com/skulpt/skulpt to be included in this benchmark as it, Brython and Transcrypt are all in this article.
https://pythontips.com/2019/05/22/running-python-in-the-browser/
Also thanks for the work, we might need a benchmark that is comprehensive, which compares:
- native Python
  - CPython
  - Python compilers including Cython and Nutika
  - JITs including PyPy and Numba
- native JS equivalents in the browser
- Python-to-JS compilers
  - Transcrypt
  - Brython
  - Skulpt

**Comment by JdeH** [comment]
Since there are many aspects that determine the useability of a compiler/interpreter, I try to stay away from direct comparison with other browser Pythons.

Having said that, code generated by Transcrypt is quite compact and runs as fast as JavaScript by good approximation.
The figures referred to by the link below give some impression.

> Note that Transcrypt avoids constructs that cannot be made to perform in the browser. This means that Transcrypt and CPython are playing in different leagues. Transcrypt makes it possible for Python programmers to take a lot of their skills to the browser, but it is in no way a replacement for CPython. The two should be regarded as complementary.

http://www.transcrypt.org/docs/html/philosophy_directions.html#why-are-certain-python-constructions-supported-as-a-local-or-global-option-rather-than-by-default

**Comment by warrenchopin** [comment]
In my experience, Brython is about 30 times slower than CPython. Transcrypt is not much different from pure Javascript if you don't use slow compiler options such as kwargs, tconv, keycheck, etc. So, I believe that Transcrypt can be over 30 times faster than Brython. Even if you use all the slow options, I think that Transcrypt is still a lot faster than Brython because Transcrypt is developed focusing on speed while Brython is focusing on compatibility to CPtyhon.

If you are developing web pages whose speed is not crucial, Brython can be a good choice because you can use standard Python expressions and libraries without big limitations. Also, keep in mind that web pages are cached in server, in client, and in proxy. So, if your web page is static or non-interactive html, you don't have to worry too much about speed of Brython.

But if you are developing an application whose speed is crucial, choosing Transcrypt is inevitable.

**Comment by JennaSys** [comment]
Closing since there have been no further comments for some time.
