### ISSUE TITLE
Accessing a non-existing key in a dict results in an uncatchable JS error "Uncaught TypeError" instead of a pythonic "KeyError" exception

### ISSUE THREAD

**Issue by halloleo** [TranscryptOrg/Transcrypt#803]
When I access a non-existing key in a dictionary, I get 

> Uncaught TypeError: rangePerColor[i] is undefined

I would have expected a Python exception like

> KeyError: 7

Furthermore, this error cannot be caught with a `try` ... `except` block.

What can I do to catch this problem?

**Comment by JennaSys** [comment]
I just ran into a scenario where I was expecting a `KeyError` caused by a missing key, but didn't get any error at all and the dictionary key lookup just returned `None` instead. According to the [Transcrypt docs](https://www.transcrypt.org/docs/html/special_facilities.html?highlight=dict#pragma-keycheck-and-pragma-nokeycheck), to resolve this, I had to use the `keycheck` pragma in order to force the Python behavior and raise a `KeyError`. To that end, I ended up with code like the following, which seemed to work as expected (note the `keycheck` single-line pragma):

```python
    try:
        target_view = router[pathname]  # __:keycheck
        return target_view(props)
    except KeyError:
        console.error(f"Invalid route: '{pathname}'")```

**Comment by halloleo** [comment]
Cool. Makes total sense. 

I wasn't aware that the behaviour here by design is different  to the standard Python behaviour -- and how to adjust it.

Thanks a lot.
